DROP USER IF EXISTS 'root'@'localhost';

DROP USER IF EXISTS 'root'@'%';

CREATE USER 'root'@'%' IDENTIFIED BY 'root';

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

ALTER USER `ROOT`@`%` IDENTIFIED WITH MYSQL_NATIVE_PASSWORD BY 'root';

FLUSH PRIVILEGES;